# This sample GitLab CI/CD configuration file that should need editing before it works on your project.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/#stages
#

# Docker image to use.
image: robertaboukhalil/emsdk:1.38.26

stages:  # List of stages for jobs, and their order of execution
  - build-deployed
  - deploy

# In project debugging terminal:
# 
#   CI_PROJECT_DIR=$(pwd);
# 

build-job:  # This job runs in the build stage, which runs first.
  stage: build-deployed
  script:
    - echo "Compiling code..."
    - echo ""
    - echo "Compile complete."

pages:
  stage: deploy
  script:
    - echo ""
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL.
      - public
  rules:
    # This ensures that only pushes to the default branch
    # will trigger a pages deploy.
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

